### ISSUE TITLE
tokenizing working incorrectly in webpack/create-react-app production build

### ISSUE THREAD

**Issue by kellyi** [winkjs/wink-sentiment#23]
Hi! Thanks so much for creating this library! I was trying it out by creating a very simple React application that will do sentiment analysis for a given text input as the input changes.

The app is here -- https://react-sentiment-analyzer.netlify.com/ -- and/but although it's working pretty well on localhost in development, when I create a production build using the webpack setup in Create-React-App it appears that the way wink-sentiment tokenizes the input string doesn't work the same way it does in development. Essentially it seems to be splitting words into smaller pieces than it does in development, which makes me think that I may be importing something incorrectly.

For example, here's the local development version which shows the wink-sentiment output for the word "angry" via Redux-devtools on the right:

<img width="1402" alt="Screen Shot 2019-04-15 at 10 07 51 PM" src="https://user-images.githubusercontent.com/4165523/56176994-119ccf80-5fcb-11e9-9a96-bde86481371e.png">

Note that it's parsing it all as a single word.

As a contrast, this is the Redux devtools output for the same word on https://react-sentiment-analyzer.netlify.com/ in a production build:

<img width="1305" alt="Screen Shot 2019-04-15 at 10 05 40 PM" src="https://user-images.githubusercontent.com/4165523/56177015-28432680-5fcb-11e9-93ef-1f73304bb38e.png">

Here it's parsing the word "angry" into two tokens: `a` and `ngry`, and thereby not outputting the same sentiment.

The code I'm using to run wink-sentiment is https://github.com/kellyi/react-sentiment-analyzer/blob/master/src/utils/sentimentAnalyzer.js ->

```
import sentiment from 'wink-sentiment';

const sentimentAnalyzer = text => sentiment(text);

export default sentimentAnalyzer;
```

Do you have any idea why wink-sentiment might be tokenizing things one way in development and another in production?

Thanks again for creating this library!

**Comment by prtksxna** [comment]
Hey @kellyi, I am glad that you found the library useful and thank you for writing such a thorough bug report 🙂.

I cloned your repository and checked out [`b140a30`](https://github.com/kellyi/react-sentiment-analyzer/commit/b140a3003ef193ea589b7fba25f384512ccc5f91) to debug this. It seems that when Webpack runs for the production build it tries to escape certain parts of our Regexp, changing 
`/[\₿\₽\₹\₨\$\£\¥\€\₩]/g` to 
`/[\u20bf\u20bd\u20b9\u20a8$\xa3\xa5\u20ac\u20a9]/g`, which is incorrect.

It doesn't seem to be making this optimization in the local build which is why that still works fine. This optimization is incorrect. Since you're using `create-react-app` you might not be able to change the configuration till you eject 🙁. 

We'll be making changes to circumvent this issue and releasing an update soon :shipit:.

**Comment by prtksxna** [comment]
@kellyi, this should be fixed now. In your `package.json` you can now add `"wink-sentiment": "^5.0.2"` to use the new version.

Thanks again for reporting the issue!

**Comment by kellyi** [comment]
Awesome! Thank you for fixing it so rapidly. I updated to use wink-sentiment 5.0.2 and it's now working as expected: https://react-sentiment-analyzer.netlify.com/

Thanks again for fixing this so quickly!
